[package]
name = "vinter_report"
version = "0.1.0"
edition = "2021"

[dependencies]
vinter_common = { path = "../vinter_common" }

anyhow = "1.0"
addr2line = "0.17.0"
clap = { version = "3.1.3", features = ["derive"] }
